version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: app_nginx
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - app

  app:
    container_name: app
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8080:5173
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: app_db
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gsm
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
